secret:
  useExistingSecret: true
  name: port-credentials

overwriteConfigurationOnRestart: true

stateKey: port-k8s-exporter

extraEnv:
  - name: CLUSTER_NAME
    value: "k3s-default"

configMap:
  config:
    - kind: Namespace
      selector:
        query: "true"
      port:
        entity:
          mappings:
            - identifier: .metadata.name + "-" + env.CLUSTER_NAME
              blueprint: '"k8s_namespace"'
              properties:
                name: .metadata.name
                creationTimestamp: .metadata.creationTimestamp
    - kind: Deployment
      selector:
        query: "true"
      port:
        entity:
          mappings:
            - identifier: .metadata.name + "-" + .metadata.namespace + "-" + env.CLUSTER_NAME
              blueprint: '"workload"'
              properties:
                name: .metadata.name
    - kind: DaemonSet
      selector:
        query: "true"
      port:
        entity:
          mappings:
            - identifier: .metadata.name + "-" + .metadata.namespace + "-" + env.CLUSTER_NAME
              blueprint: '"workload"'
              properties:
                name: .metadata.name
    - kind: StatefulSet
      selector:
        query: "true"
      port:
        entity:
          mappings:
            - identifier: .metadata.name + "-" + .metadata.namespace + "-" + env.CLUSTER_NAME
              blueprint: '"workload"'
              properties:
                name: .metadata.name
    - kind: Service
      selector:
        query: "true"
      port:
        entity:
          mappings:
            - identifier: .metadata.name + "-" + .metadata.namespace + "-" + env.CLUSTER_NAME
              blueprint: '"service"'
              properties:
                name: .metadata.name
                type: .spec.type
    - kind: Ingress
      selector:
        query: "true"
      port:
        entity:
          mappings:
            - identifier: .metadata.namespace + "-" + .metadata.name + "-" + env.CLUSTER_NAME
              blueprint: '"ingress"'
              properties:
                name: .metadata.name
                namespace: .metadata.namespace
                creationTimestamp: .metadata.creationTimestamp
                host: .spec.rules[0].host // ""
                path: .spec.rules[0].http.paths[0].path // "/"
                tls: .spec.tls != null
    - kind: Pod
      selector:
        query: "true"
      port:
        entity:
          mappings:
            - identifier: .metadata.name + "-" + .metadata.namespace + "-" + env.CLUSTER_NAME
              blueprint: '"k8s_pod"'
              properties:
                name: .metadata.name
